name: Build, Release & Sync
on:
  push:
    branches:
      - main

jobs:
  build_and_release:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/hydrogen'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build Library
        run: npm run build
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
  sync_branches:
    name: Sync Branches
    needs: build_and_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge main -> develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/main --ff --message "chore: merge changes in main back into develop [skip ci]"
          git push
