name: Sync develop after release
on:
  registry_package:
    types: [published]

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Merge main -> develop
        run: |
          git fetch origin
          git checkout develop
          git merge origin/main --ff --message "chore: merge changes in main back into develop [skip ci]"
          git push

